name: Image Compression

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Build Docker image
        run: docker build -t simage .

      - name: Install dependencies
        run: npm install

      - name: Check Squoosh CLI version
        run: npx @squoosh/cli --version

      - name: Install @squoosh/cli globally
        run: npm install -g @squoosh/cli@0.7.3

      - name: Show installed @squoosh/cli details
        run: npm list @squoosh/cli

      - name: Compress Images
        run: node src/index.js
        env:
          INPUT: './input'
          OUTPUT: './output'
          BACKUP: './backup'

      - name: Install tree command
        run: |
          if ! command -v tree &> /dev/null
          then
              echo "Installing tree..."
              sudo apt-get update
              sudo apt-get install tree
          else
              echo "Tree is already installed."
          fi

      - name: Print directory tree
        run: tree -L 2