name: Image Compression

on:
  push:
    paths:
      - 'src/**'
      - 'images/**'

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Compress Images
        run: node src/index.js
        env:
          path: './images'
          output-path: './output'
          backup-path: './backup'
